import { Dimensions } from "react-native";

export const COLORS = {
  light: {
    primaryBg: "#FFFFFF",
    secondaryBg: "#F7F8FA",
    primaryText: "#1A1A1A",
    secondaryText: "#6B6B6B",
    accent: "#007AFF",
  },

  dark: {
    primaryBg: "#0E1113",
    secondaryBg: "#1A1D20",
    primaryText: "#F5F6F8",
    secondaryText: "#A0A4A8",
    accent: "#4DA3FF",
  },
};

export const SIZES = {
  height: Dimensions.get("window").height,
  width: Dimensions.get("window").width,
};

export const questions: questionType[] = [
  {
    q: "What does HTML stand for?",
    id: 1,
    options: {
      A: "High Transfer Machine Logic",
      B: "Hyper Tool Multi Language",
      C: "Hyper Text Markup Language",
      D: "Hyper Transfer Markup Logic",
    },
    correct: "C",
  },
  {
    q: "Which company developed the Java programming language?",
    id: 2,
    options: {
      A: "Microsoft",
      B: "Sun Microsystems",
      C: "IBM",
      D: "Google",
    },
    correct: "B",
  },
  {
    q: "What does CSS stand for?",
    id: 3,
    options: {
      A: "Computer Style Syntax",
      B: "Cascading Style Sheets",
      C: "Creative Style System",
      D: "Colorful Style Setup",
    },
    correct: "B",
  },
  {
    q: "React.js is mainly used for building what?",
    id: 4,
    options: {
      A: "APIs",
      B: "Databases",
      C: "User Interfaces",
      D: "Operating Systems",
    },
    correct: "C",
  },
  {
    q: "Who is known as the father of the computer?",
    id: 5,
    options: {
      A: "Alan Turing",
      B: "Bill Gates",
      C: "Charles Babbage",
      D: "Steve Jobs",
    },
    correct: "C",
  },
  {
    q: "Which language is primarily used for Android app development?",
    id: 6,
    options: {
      A: "Swift",
      B: "JavaScript",
      C: "Kotlin",
      D: "C#",
    },
    correct: "C",
  },
  {
    q: "What year was the first iPhone released?",
    id: 7,
    options: {
      A: "2005",
      B: "2009",
      C: "2010",
      D: "2007",
    },
    correct: "D",
  },
  {
    q: "Which company owns GitHub?",
    id: 8,
    options: {
      A: "Google",
      B: "Microsoft",
      C: "Apple",
      D: "Amazon",
    },
    correct: "B",
  },
  {
    q: "What does API stand for?",
    id: 9,
    options: {
      A: "Automated Program Integration",
      B: "Application Programming Interface",
      C: "Applied Programming Input",
      D: "Advanced Processing Interface",
    },
    correct: "B",
  },
  {
    q: "Which programming language was developed by Guido van Rossum?",
    id: 10,
    options: {
      A: "Ruby",
      B: "C++",
      C: "Python",
      D: "Go",
    },
    correct: "C",
  },
  {
    q: "What is the default port for HTTP?",
    id: 11,
    options: {
      A: "8080",
      B: "21",
      C: "80",
      D: "443",
    },
    correct: "C",
  },
  {
    q: "What is the default port for HTTPS?",
    id: 12,
    options: {
      A: "22",
      B: "8080",
      C: "443",
      D: "110",
    },
    correct: "C",
  },
  {
    q: "Which company created the Chrome browser?",
    id: 13,
    options: {
      A: "Microsoft",
      B: "Google",
      C: "Apple",
      D: "Mozilla",
    },
    correct: "B",
  },
  {
    q: "Which of these is a NoSQL database?",
    id: 14,
    options: {
      A: "MySQL",
      B: "PostgreSQL",
      C: "MongoDB",
      D: "Oracle",
    },
    correct: "C",
  },
  {
    q: "What does SQL stand for?",
    id: 15,
    options: {
      A: "Sequential Query Logic",
      B: "Structured Query Language",
      C: "Standard Question Language",
      D: "System Query Logic",
    },
    correct: "B",
  },
  {
    q: "What does JSON stand for?",
    id: 16,
    options: {
      A: "Java Syntax Object Naming",
      B: "JavaScript Object Notation",
      C: "Joined Syntax Oriented Notation",
      D: "Java Object Navigation",
    },
    correct: "B",
  },
  {
    q: "Which company developed TypeScript?",
    id: 17,
    options: {
      A: "Google",
      B: "Meta",
      C: "Oracle",
      D: "Microsoft",
    },
    correct: "D",
  },
  {
    q: "Which of these is a JavaScript framework?",
    id: 18,
    options: {
      A: "Laravel",
      B: "Django",
      C: "Flask",
      D: "React",
    },
    correct: "D",
  },
  {
    q: "Which HTML tag is used to link external CSS files?",
    id: 19,
    options: {
      A: "<style>",
      B: "<css>",
      C: "<link>",
      D: "<script>",
    },
    correct: "C",
  },
  {
    q: "Which symbol is used for comments in JavaScript?",
    id: 20,
    options: {
      A: "##",
      B: "--",
      C: "//",
      D: "/* */",
    },
    correct: "C",
  },
  {
    q: "Which programming language runs in a web browser?",
    id: 21,
    options: {
      A: "Python",
      B: "JavaScript",
      C: "C++",
      D: "Rust",
    },
    correct: "B",
  },
  {
    q: "In React, what is JSX?",
    id: 22,
    options: {
      A: "JSON Extension",
      B: "Java Syntax Extension",
      C: "JavaScript XML",
      D: "JavaScript Syntax",
    },
    correct: "C",
  },
  {
    q: "Which command initializes a new Git repository?",
    id: 23,
    options: {
      A: "git start",
      B: "git new",
      C: "git begin",
      D: "git init",
    },
    correct: "D",
  },
  {
    q: "What year was JavaScript created?",
    id: 24,
    options: {
      A: "2000",
      B: "1995",
      C: "1990",
      D: "1998",
    },
    correct: "B",
  },
  {
    q: "Who created the World Wide Web?",
    id: 25,
    options: {
      A: "Bill Gates",
      B: "Steve Jobs",
      C: "Mark Zuckerberg",
      D: "Tim Berners-Lee",
    },
    correct: "D",
  },
  {
    q: "Which company created the Swift programming language?",
    id: 26,
    options: {
      A: "Google",
      B: "Microsoft",
      C: "IBM",
      D: "Apple",
    },
    correct: "D",
  },
  {
    q: "Which of the following is a version control system?",
    id: 27,
    options: {
      A: "Docker",
      B: "Node.js",
      C: "Git",
      D: "Nginx",
    },
    correct: "C",
  },
  {
    q: "Which cloud platform is developed by Amazon?",
    id: 28,
    options: {
      A: "Azure",
      B: "AWS",
      C: "Google Cloud",
      D: "Oracle Cloud",
    },
    correct: "B",
  },
  {
    q: "What is the primary function of Docker?",
    id: 29,
    options: {
      A: "Virtualization",
      B: "Containerization",
      C: "Version Control",
      D: "Automation",
    },
    correct: "B",
  },
  {
    q: "Which database uses structured tables?",
    id: 30,
    options: {
      A: "MongoDB",
      B: "Redis",
      C: "Elasticsearch",
      D: "MySQL",
    },
    correct: "D",
  },
  {
    q: "Which command is used to install packages in Node.js?",
    id: 31,
    options: {
      A: "node install",
      B: "npm install",
      C: "install npm",
      D: "npm get",
    },
    correct: "B",
  },
  {
    q: "What does 'npm' stand for?",
    id: 32,
    options: {
      A: "Network Project Manager",
      B: "Node Package Manager",
      C: "New Programming Module",
      D: "Node Programming Machine",
    },
    correct: "B",
  },
  {
    q: "What is React Native primarily used for?",
    id: 33,
    options: {
      A: "Desktop Applications",
      B: "Mobile App Development",
      C: "Game Design",
      D: "Database Management",
    },
    correct: "B",
  },
  {
    q: "Who is the founder of Microsoft?",
    id: 34,
    options: {
      A: "Steve Jobs",
      B: "Larry Page",
      C: "Bill Gates",
      D: "Jeff Bezos",
    },
    correct: "C",
  },
  {
    q: "Which protocol is used to send emails?",
    id: 35,
    options: {
      A: "HTTP",
      B: "FTP",
      C: "SMTP",
      D: "IMAP",
    },
    correct: "C",
  },
  {
    q: "Which company created Android?",
    id: 36,
    options: {
      A: "Apple",
      B: "Google",
      C: "Samsung",
      D: "Nokia",
    },
    correct: "B",
  },
  {
    q: "Which file extension is used for JavaScript files?",
    id: 37,
    options: {
      A: ".jsx",
      B: ".java",
      C: ".js",
      D: ".json",
    },
    correct: "C",
  },
  {
    q: "What does CPU stand for?",
    id: 38,
    options: {
      A: "Computer Program Utility",
      B: "Central Processing Unit",
      C: "Central Program Unit",
      D: "Control Processing Utility",
    },
    correct: "B",
  },
  {
    q: "Which company created the Windows operating system?",
    id: 39,
    options: {
      A: "Apple",
      B: "Microsoft",
      C: "IBM",
      D: "Google",
    },
    correct: "B",
  },
  {
    q: "Which language is used for web styling?",
    id: 40,
    options: {
      A: "HTML",
      B: "Python",
      C: "C++",
      D: "CSS",
    },
    correct: "D",
  },
  {
    q: "Which operating system is developed by Apple?",
    id: 41,
    options: {
      A: "Windows",
      B: "Linux",
      C: "macOS",
      D: "Ubuntu",
    },
    correct: "C",
  },
  {
    q: "Which programming language is used to write smart contracts on Ethereum?",
    id: 42,
    options: {
      A: "Python",
      B: "Solidity",
      C: "Go",
      D: "Rust",
    },
    correct: "B",
  },
  {
    q: "What does AI stand for?",
    id: 43,
    options: {
      A: "Applied Information",
      B: "Algorithmic Integration",
      C: "Artificial Intelligence",
      D: "Automated Input",
    },
    correct: "C",
  },
  {
    q: "What is the most popular version control system?",
    id: 44,
    options: {
      A: "Git",
      B: "Mercurial",
      C: "SVN",
      D: "CVS",
    },
    correct: "A",
  },
  {
    q: "Which company developed the Go programming language?",
    id: 45,
    options: {
      A: "Apple",
      B: "IBM",
      C: "Microsoft",
      D: "Google",
    },
    correct: "D",
  },
  {
    q: "Which symbol is used for ID selectors in CSS?",
    id: 46,
    options: {
      A: "#",
      B: "@",
      C: ".",
      D: "$",
    },
    correct: "A",
  },
  {
    q: "Which company created the Flutter framework?",
    id: 47,
    options: {
      A: "Meta",
      B: "Amazon",
      C: "Google",
      D: "Microsoft",
    },
    correct: "C",
  },
  {
    q: "What does URL stand for?",
    id: 48,
    options: {
      A: "Uniform Resource Locator",
      B: "Unified Reference Locator",
      C: "Universal Routing Link",
      D: "Uniform Retrieval Link",
    },
    correct: "A",
  },
  {
    q: "Which of the following is a backend JavaScript framework?",
    id: 49,
    options: {
      A: "Vue.js",
      B: "Node.js",
      C: "Angular",
      D: "React.js",
    },
    correct: "B",
  },
  {
    q: "What is the main function of a firewall?",
    id: 50,
    options: {
      A: "Backup Management",
      B: "Network Security",
      C: "File Storage",
      D: "Data Compression",
    },
    correct: "B",
  },
  {
    q: "Who founded Facebook?",
    id: 51,
    options: {
      A: "Mark Zuckerberg",
      B: "Elon Musk",
      C: "Larry Page",
      D: "Jeff Bezos",
    },
    correct: "A",
  },
  {
    q: "Which markup language is used to structure web pages?",
    id: 52,
    options: {
      A: "CSS",
      B: "JavaScript",
      C: "HTML",
      D: "PHP",
    },
    correct: "C",
  },
  {
    q: "Which of these is a frontend framework?",
    id: 53,
    options: {
      A: "Express",
      B: "Angular",
      C: "Django",
      D: "Laravel",
    },
    correct: "B",
  },
  {
    q: "Which data structure uses FIFO (First In First Out)?",
    id: 54,
    options: {
      A: "Tree",
      B: "Queue",
      C: "Stack",
      D: "Graph",
    },
    correct: "B",
  },
  {
    q: "Which programming language uses 'print()' to display output?",
    id: 55,
    options: {
      A: "C",
      B: "Python",
      C: "Java",
      D: "JavaScript",
    },
    correct: "B",
  },
  {
    q: "Which command is used to clone a Git repository?",
    id: 56,
    options: {
      A: "git get",
      B: "git fork",
      C: "git copy",
      D: "git clone",
    },
    correct: "D",
  },
  {
    q: "Which of the following is a cloud storage service?",
    id: 57,
    options: {
      A: "Google Drive",
      B: "Docker",
      C: "Notepad",
      D: "Git",
    },
    correct: "A",
  },
  {
    q: "What is the most widely used operating system in the world?",
    id: 58,
    options: {
      A: "Windows",
      B: "Android",
      C: "iOS",
      D: "Linux",
    },
    correct: "B",
  },
  {
    q: "Which tool is used to manage project dependencies in JavaScript?",
    id: 59,
    options: {
      A: "composer",
      B: "npm",
      C: "pip",
      D: "gradle",
    },
    correct: "B",
  },
  {
    q: "What is the main purpose of GitHub?",
    id: 60,
    options: {
      A: "Hosting and collaborating on code",
      B: "Creating designs",
      C: "Editing images",
      D: "Running applications",
    },
    correct: "A",
  },
  {
    q: "Which programming language is used in data science?",
    id: 61,
    options: {
      A: "Swift",
      B: "C",
      C: "PHP",
      D: "Python",
    },
    correct: "D",
  },
  {
    q: "Which of the following is a JavaScript runtime?",
    id: 62,
    options: {
      A: "Angular",
      B: "Node.js",
      C: "React",
      D: "Vue",
    },
    correct: "B",
  },
  {
    q: "What does DOM stand for?",
    id: 63,
    options: {
      A: "Document Object Model",
      B: "Data Object Management",
      C: "Digital Object Map",
      D: "Document Order Method",
    },
    correct: "A",
  },
  {
    q: "Which tag is used to define a JavaScript file in HTML?",
    id: 64,
    options: {
      A: "<js>",
      B: "<script>",
      C: "<javascript>",
      D: "<code>",
    },
    correct: "B",
  },
  {
    q: "Which of these is a Python web framework?",
    id: 65,
    options: {
      A: "React",
      B: "Django",
      C: "Laravel",
      D: "Angular",
    },
    correct: "B",
  },
  {
    q: "Which of these is a relational database?",
    id: 66,
    options: {
      A: "MongoDB",
      B: "PostgreSQL",
      C: "Redis",
      D: "Firebase",
    },
    correct: "B",
  },
  {
    q: "What does GPU stand for?",
    id: 67,
    options: {
      A: "Graphical Program Utility",
      B: "Graphics Processing Unit",
      C: "General Processing Unit",
      D: "Graphics Power Utility",
    },
    correct: "B",
  },
  {
    q: "Which of these companies was founded first?",
    id: 68,
    options: {
      A: "IBM",
      B: "Apple",
      C: "Microsoft",
      D: "Google",
    },
    correct: "A",
  },
  {
    q: "What is the extension of a TypeScript file?",
    id: 69,
    options: {
      A: ".tsx",
      B: ".ts",
      C: ".js",
      D: ".jsx",
    },
    correct: "B",
  },
  {
    q: "Which of the following is a Linux distribution?",
    id: 70,
    options: {
      A: "macOS",
      B: "iOS",
      C: "Ubuntu",
      D: "Windows",
    },
    correct: "C",
  },
  {
    q: "Which data structure uses LIFO (Last In First Out)?",
    id: 71,
    options: {
      A: "Stack",
      B: "Queue",
      C: "Tree",
      D: "Array",
    },
    correct: "A",
  },
  {
    q: "Which company developed the Android OS?",
    id: 72,
    options: {
      A: "Samsung",
      B: "Google",
      C: "Apple",
      D: "Nokia",
    },
    correct: "B",
  },
  {
    q: "Which company owns the Chrome browser?",
    id: 73,
    options: {
      A: "Google",
      B: "Microsoft",
      C: "Mozilla",
      D: "Apple",
    },
    correct: "A",
  },
  {
    q: "What does HTTP stand for?",
    id: 74,
    options: {
      A: "HyperText Transfer Protocol",
      B: "High Transfer Text Protocol",
      C: "HyperTool Transfer Protocol",
      D: "HyperText Transmission Process",
    },
    correct: "A",
  },
  {
    q: "Which of the following is a JavaScript framework maintained by Google?",
    id: 75,
    options: {
      A: "React",
      B: "Angular",
      C: "Vue",
      D: "Svelte",
    },
    correct: "B",
  },
  {
    q: "Which of these devices stores permanent data?",
    id: 76,
    options: {
      A: "RAM",
      B: "Hard Drive",
      C: "Cache",
      D: "Registers",
    },
    correct: "B",
  },
  {
    q: "Which company created the iPad?",
    id: 77,
    options: {
      A: "Apple",
      B: "Microsoft",
      C: "Samsung",
      D: "Dell",
    },
    correct: "A",
  },
  {
    q: "What programming language is mainly used for iOS development?",
    id: 78,
    options: {
      A: "Swift",
      B: "Java",
      C: "Kotlin",
      D: "C++",
    },
    correct: "A",
  },
  {
    q: "Which company developed the Visual Studio Code editor?",
    id: 79,
    options: {
      A: "Microsoft",
      B: "Google",
      C: "Meta",
      D: "Apple",
    },
    correct: "A",
  },
  {
    q: "Which of these is a JavaScript package manager?",
    id: 80,
    options: {
      A: "gradle",
      B: "npm",
      C: "pip",
      D: "composer",
    },
    correct: "B",
  },
];
